version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: swiitchbank-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - swiitchbank-net

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: swiitchbank-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - swiitchbank-net

  db:
    image: postgres:14
    container_name: swiitchbank-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - swiitchbank-net

  redis:
    image: redis:6
    container_name: swiitchbank-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - swiitchbank-net

volumes:
  postgres-data:

networks:
  swiitchbank-net:
    driver: bridge